language: go

go:
#  - tip     # tip is too slow
  - 1.12.x
  - 1.11.x

install:
  - export GOPROXY=https://proxy.golang.org
  - export GO111MODULE=on
  - go mod init gitub.com/swaggest/form && go mod vendor && rm go.mod
  - export GO111MODULE=

script:
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)